import { extname } from 'node:path';

export type AttachmentCategory='image'|'document'|'audio'|'video'|'archive';
export type AttachmentAnalysis='text'|'vision'|'unavailable';
export interface AttachmentCapability { extension:string; category:AttachmentCategory; contentType:string; declaredTypes:readonly string[]; analysis:AttachmentAnalysis }
const cap=(extension:string,category:AttachmentCategory,contentType:string,analysis:AttachmentAnalysis,...aliases:string[]):AttachmentCapability=>({extension,category,contentType,analysis,declaredTypes:[contentType,...aliases]});
/** Authoritative upload capability matrix. Validation, limits and parser routing derive from it. */
export const ATTACHMENT_CAPABILITIES:Readonly<Record<string,AttachmentCapability>>=Object.freeze(Object.fromEntries([
 cap('jpg','image','image/jpeg','vision','image/jpg'),cap('jpeg','image','image/jpeg','vision','image/jpg'),cap('png','image','image/png','vision'),cap('gif','image','image/gif','unavailable'),cap('webp','image','image/webp','vision'),cap('heic','image','image/heic','vision','image/heic-sequence'),cap('heif','image','image/heif','vision','image/heif-sequence'),
 cap('pdf','document','application/pdf','text'),cap('txt','document','text/plain','text'),cap('md','document','text/markdown','text','text/plain'),cap('csv','document','text/csv','text','text/plain','application/vnd.ms-excel'),cap('json','document','application/json','text','text/plain'),cap('rtf','document','application/rtf','unavailable','text/rtf'),
 cap('doc','document','application/msword','unavailable'),cap('xls','document','application/vnd.ms-excel','unavailable'),cap('ppt','document','application/vnd.ms-powerpoint','unavailable'),cap('docx','document','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text'),cap('xlsx','document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text'),cap('pptx','document','application/vnd.openxmlformats-officedocument.presentationml.presentation','text'),cap('odt','document','application/vnd.oasis.opendocument.text','text'),cap('ods','document','application/vnd.oasis.opendocument.spreadsheet','text'),cap('odp','document','application/vnd.oasis.opendocument.presentationml.presentation','text'),
 cap('mp3','audio','audio/mpeg','unavailable','audio/mp3'),cap('m4a','audio','audio/mp4','unavailable','audio/x-m4a'),cap('aac','audio','audio/aac','unavailable'),cap('wav','audio','audio/wav','unavailable','audio/x-wav'),cap('ogg','audio','audio/ogg','unavailable','application/ogg'),cap('opus','audio','audio/opus','unavailable','audio/ogg'),cap('flac','audio','audio/flac','unavailable','audio/x-flac'),
 cap('mp4','video','video/mp4','unavailable'),cap('m4v','video','video/x-m4v','unavailable','video/mp4'),cap('mov','video','video/quicktime','unavailable'),cap('webm','video','video/webm','unavailable'),cap('mpeg','video','video/mpeg','unavailable','video/mpg'),cap('zip','archive','application/zip','unavailable','application/x-zip-compressed'),
].map(x=>[x.extension,x])));

const MIB=1024*1024;
const defaults:Record<AttachmentCategory,number>={image:20*MIB,document:20*MIB,audio:25*MIB,video:25*MIB,archive:20*MIB};
export function attachmentLimit(category:AttachmentCategory):number{const n=Number(process.env[`JOSI_ATTACHMENT_${category.toUpperCase()}_MAX_BYTES`]);return Number.isSafeInteger(n)&&n>0&&n<=100*MIB?n:defaults[category];}
export const maxAttachmentLimit=()=>Math.max(...(Object.keys(defaults) as AttachmentCategory[]).map(attachmentLimit));
export interface ContractFailure{status:number;code:string;message:string}
const fail=(status:number,code:string,message:string):never=>{throw {attachmentContractFailure:true,status,code,message} satisfies ContractFailure&{attachmentContractFailure:true};};
const prefix=(b:Buffer,hex:string)=>b.subarray(0,hex.length/2).equals(Buffer.from(hex,'hex'));
const contentFail=():never=>fail(415,'file_content_mismatch','The bytes are malformed, truncated, or do not match the declared file format.');
export function sanitizeAttachmentName(original:string):string{const name=original.normalize('NFC').replace(/[\\/\x00-\x1f\x7f\u202a-\u202e\u2066-\u2069]/g,'_').replace(/^\.+/,'').replace(/[ .]+$/g,'').slice(0,240);if(!name)fail(400,'invalid_filename','Choose a file with a valid name.');return name;}
function riff(b:Buffer,kind:string){return b.length>=12&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)===kind&&b.readUInt32LE(4)+8===b.length;}
function png(b:Buffer){if(!prefix(b,'89504e470d0a1a0a'))return false;let p=8,ihdr=false;while(p+12<=b.length){const n=b.readUInt32BE(p),t=b.toString('ascii',p+4,p+8);if(n>64*MIB||p+12+n>b.length)return false;if(!ihdr&&t!=='IHDR')return false;if(t==='IHDR')ihdr=n===13;if(t==='IEND')return ihdr&&n===0&&p+12===b.length;p+=12+n;}return false;}
function bmff(b:Buffer,brands:Set<string>,required='moov'){let p=0,brand=false,has=false;if(b.length<24)return false;while(p+8<=b.length){let n=b.readUInt32BE(p);const type=b.toString('ascii',p+4,p+8);if(n===1){if(p+16>b.length)return false;n=Number(b.readBigUInt64BE(p+8));}if(n<8||p+n>b.length)return false;if(type==='ftyp')for(let q=p+8;q+4<=p+n;q+=4)brand ||= brands.has(b.toString('ascii',q,q+4));if(type===required)has=true;p+=n;}return p===b.length&&brand&&has;}
const unsafeZip=/(^|\/)(?:\.\.?)(?:\/|$)|\.(?:exe|dll|com|scr|msi|bat|cmd|ps1|sh|js|jse|vbs|vbe|wsf|hta|lnk|app|dylib|so|class|jar|apk|ipa|deb|rpm|docm|dotm|xlsm|xltm|pptm|potm|ppam|svg|html?|xhtml)$/i;
function zipNames(b:Buffer):string[]{if(!prefix(b,'504b0304'))fail(415,'archive_polyglot','ZIP packages with prefixed or polyglot content are not accepted.');let e=-1;for(let p=b.length-22;p>=Math.max(0,b.length-65557);p--)if(b.readUInt32LE(p)===0x06054b50){e=p;break;}if(e<0||e+22>b.length)fail(415,'archive_malformed','The ZIP package is malformed or truncated.');const count=b.readUInt16LE(e+10),size=b.readUInt32LE(e+12),offset=b.readUInt32LE(e+16),comment=b.readUInt16LE(e+20);if(e+22+comment!==b.length||count>2000||size>8*MIB||offset+size!==e)fail(415,'archive_bounds','The ZIP central directory exceeds safe inspection limits.');let p=offset,total=0;const names:string[]=[];for(let i=0;i<count;i++){if(p+46>e||b.readUInt32LE(p)!==0x02014b50)fail(415,'archive_malformed','The ZIP central directory is inconsistent.');const flags=b.readUInt16LE(p+8),method=b.readUInt16LE(p+10),compressed=b.readUInt32LE(p+20),expanded=b.readUInt32LE(p+24),nl=b.readUInt16LE(p+28),xl=b.readUInt16LE(p+30),cl=b.readUInt16LE(p+32),local=b.readUInt32LE(p+42);const localName=local+30<=b.length?b.readUInt16LE(local+26):0,localExtra=local+30<=b.length?b.readUInt16LE(local+28):0;if(flags&1||![0,8].includes(method)||p+46+nl+xl+cl>e||local+30+localName+localExtra+compressed>offset||b.readUInt32LE(local)!==0x04034b50)fail(415,'archive_malformed','Encrypted, unsupported, or malformed ZIP entries are not accepted.');let name='';try{name=new TextDecoder('utf-8',{fatal:true}).decode(b.subarray(p+46,p+46+nl)).replace(/\\/g,'/');}catch{fail(415,'archive_malformed','ZIP entry names must be valid UTF-8.');}if(!name||name.startsWith('/')||unsafeZip.test(name)||name.includes('\0'))fail(415,'archive_active_content','ZIP packages containing executable or unsafe paths are not accepted.');total+=expanded;if(total>100*MIB)fail(415,'archive_expanded_size','The ZIP package expands beyond the 100 MB safety limit.');names.push(name);p+=46+nl+xl+cl;}if(p!==e||new Set(names).size!==names.length)fail(415,'archive_malformed','The ZIP central directory is inconsistent.');return names;}
function ole(ext:string,b:Buffer){if(b.length<512||!prefix(b,'d0cf11e0a1b11ae1')||b.readUInt16LE(28)!==0xfffe||![9,12].includes(b.readUInt16LE(30)))return false;const s=b.toString('utf16le');if(/VBA|Macros|_VBA_PROJECT|Ole10Native/i.test(s))fail(415,'active_content','Macro-enabled or embedded active Office content is not accepted.');return ext==='doc'?s.includes('WordDocument'):ext==='xls'?(/Workbook|Book/.test(s)):s.includes('PowerPoint Document');}
function magic(ext:string,b:Buffer){
 if(prefix(b,'4d5a')||prefix(b,'7f454c46')||b.subarray(0,2).toString()==='#!'||b.includes(Buffer.from('EICAR-STANDARD-ANTIVIRUS-TEST-FILE')))fail(415,'executable_content','Executable or malware-test content is not accepted.');
 if(['jpg','jpeg'].includes(ext)){if(b.length<4||!prefix(b,'ffd8ff')||!b.subarray(-2).equals(Buffer.from('ffd9','hex')))contentFail();return;}if(ext==='png'){if(!png(b))contentFail();return;}if(ext==='gif'){if(!['GIF87a','GIF89a'].includes(b.toString('ascii',0,6))||b.at(-1)!==0x3b)contentFail();return;}if(ext==='webp'){if(!riff(b,'WEBP'))contentFail();return;}
 if(ext==='pdf'){const s=b.toString('latin1');if(!s.startsWith('%PDF-')||!/%%EOF\s*$/.test(s))contentFail();if(/\/(?:JavaScript|JS|Launch|EmbeddedFile|RichMedia|OpenAction|AA)\b/.test(s))fail(415,'active_content','Active PDF content is not accepted.');return;}
 if(['txt','md','csv'].includes(ext)){try{new TextDecoder('utf-8',{fatal:true}).decode(b);}catch{contentFail();}if(b.includes(0))contentFail();return;}if(ext==='json'){try{new TextDecoder('utf-8',{fatal:true}).decode(b);JSON.parse(b.toString('utf8'));}catch{fail(415,'invalid_json','JSON attachments must contain one valid UTF-8 JSON value.');}return;}if(ext==='rtf'){const s=b.toString('latin1');if(!/^\{\\rtf[1-9]/.test(s)||!/\}\s*$/.test(s))contentFail();return;}
 if(['doc','xls','ppt'].includes(ext)){if(!ole(ext,b))contentFail();return;}if(['docx','xlsx','pptx','odt','ods','odp','zip'].includes(ext)){const names=zipNames(b);if(ext==='zip')return;const required=ext==='docx'?'word/document.xml':ext==='xlsx'?'xl/workbook.xml':ext==='pptx'?'ppt/presentation.xml':'content.xml';if(!names.includes(required))contentFail();if(names.some(n=>/(?:vbaProject|embeddings|activeX|customUI|object|\.bin$)/i.test(n)))fail(415,'active_content','Macros, embedded objects, and active package content are not accepted.');return;}
 if(ext==='mp3'){let p=0;if(b.toString('ascii',0,3)==='ID3'&&b.length>=10)p=10+((b[6]&127)<<21|(b[7]&127)<<14|(b[8]&127)<<7|(b[9]&127));if(p+4>b.length||b[p]!==0xff||(b[p+1]&0xe0)!==0xe0)contentFail();return;}if(ext==='aac'){if(b.length<7||b[0]!==0xff||(b[1]&0xf6)!==0xf0)contentFail();return;}if(ext==='wav'){if(!riff(b,'WAVE')||!b.includes(Buffer.from('fmt '))||!b.includes(Buffer.from('data')))contentFail();return;}if(['ogg','opus'].includes(ext)){if(!prefix(b,'4f676753')||b.length<32)contentFail();const opus=b.includes(Buffer.from('OpusHead'));if(ext==='opus'&&!opus)contentFail();if(ext==='ogg'&&!opus&&!b.includes(Buffer.from('vorbis'))&&!b.includes(Buffer.from('fLaC')))contentFail();return;}if(ext==='flac'){if(!prefix(b,'664c6143')||b.length<8)contentFail();return;}
 if(ext==='m4a'){if(!bmff(b,new Set(['M4A ','M4B ','mp41','mp42','isom'])))contentFail();return;}if(['mp4','m4v','mov'].includes(ext)){const brands=ext==='mov'?new Set(['qt  ']):new Set(['isom','iso2','mp41','mp42','avc1','M4V ']);if(!bmff(b,brands))contentFail();return;}if(ext==='webm'){if(!prefix(b,'1a45dfa3')||!b.includes(Buffer.from('webm'))||!b.includes(Buffer.from('18538067','hex')))contentFail();return;}if(ext==='mpeg'){if(!(prefix(b,'000001ba')||prefix(b,'000001b3'))||b.length<12)contentFail();return;}contentFail();
}
export interface AttachmentContractResult{filename:string;extension:string;contentType:string;category:AttachmentCategory;analysis:{status:'available'|'unavailable';kind?:'text'|'vision';code?:string;reason?:string}}
export function validateAttachmentContract(original:string,claimedType:string,bytes:Buffer):AttachmentContractResult{
 if(!bytes.length)fail(400,'empty_file','That file is empty. Choose a file with content.');const filename=sanitizeAttachmentName(original),extension=extname(filename).slice(1).toLowerCase();if(extension==='avi')fail(415,'avi_validation_unavailable','AVI is not accepted because this runtime cannot strictly validate its codecs and container structure. Convert it to MP4, MOV, or WebM.');const c=ATTACHMENT_CAPABILITIES[extension];if(!c)fail(415,'file_type_unsupported','That file type is not supported.');const limit=attachmentLimit(c.category);if(bytes.length>limit)fail(413,'file_size_limit',`That ${c.category} exceeds its ${Math.floor(limit/MIB)} MB upload limit.`);const declared=claimedType.toLowerCase().split(';',1)[0]?.trim()||'';if(!declared||declared==='application/octet-stream'||!c.declaredTypes.includes(declared))fail(415,'mime_mismatch','The declared MIME type does not match the normalized file extension.');magic(extension,bytes);return{filename,extension,contentType:c.contentType,category:c.category,analysis:c.analysis==='unavailable'?{status:'unavailable',code:'analysis_unavailable',reason:'Stored safely, but this runtime has no approved parser for this format.'}:{status:'available',kind:c.analysis}};
}
export function isAttachmentContractFailure(value:unknown):value is ContractFailure{return !!value&&typeof value==='object'&&(value as {attachmentContractFailure?:unknown}).attachmentContractFailure===true;}
