import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Badge, Button, Card, CardTitle, Copyable, ErrorNote, Input } from '@/components/ui';
interface Status { initialized:boolean; locked:boolean; keyVersion:number; recoveryFingerprint:string|null; boxes:number; items:number; recentFailures:number; lastFailureAt:string|null }
export function AdminVault(){
 const [status,setStatus]=useState<Status|null>(null),[password,setPassword]=useState(''),[recoveryInput,setRecoveryInput]=useState(''),[oneTimeKey,setOneTimeKey]=useState<{key:string;fingerprint:string}|null>(null),[error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await api.get<{status:Status}>('/admin/vault');setStatus(r.status);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not read Vault health.');}},[]);useEffect(()=>{void load();},[load]);
 async function lock(locked:boolean){setBusy(true);try{await api.put('/admin/vault/lock',{password,locked});setPassword('');await load();}catch(e){setError(e instanceof Error?e.message:'Could not change the lock.');}finally{setBusy(false);}}
 async function initialize(){setBusy(true);try{const r=await api.post<{recoveryKey:string;fingerprint:string}>('/admin/vault/initialize',{password});setOneTimeKey({key:r.recoveryKey,fingerprint:r.fingerprint});setPassword('');await load();}catch(e){setError(e instanceof Error?e.message:'Could not initialize the Vault.');}finally{setBusy(false);}}
 async function recover(){setBusy(true);try{await api.post('/admin/vault/recover',{password,recoveryKey:recoveryInput});setPassword('');setRecoveryInput('');await load();}catch(e){setError(e instanceof Error?e.message:'Recovery failed.');}finally{setBusy(false);}}
 return <div className="mx-auto w-full max-w-3xl space-y-4"><div><h1 className="text-xl font-semibold">Master Vault</h1><p className="text-sm text-muted-foreground">Health and emergency controls. Administrators cannot view user secrets.</p></div>{error?<ErrorNote>{error}</ErrorNote>:null}
 {oneTimeKey?<Card><CardTitle>Save this recovery key offline now</CardTitle><p className="mb-3 text-sm text-muted-foreground">This is the only display. Losing both this and the installation key makes every Vault item unrecoverable.</p><Copyable label={`Recovery key · fingerprint ${oneTimeKey.fingerprint}`} value={oneTimeKey.key}/><Button variant="secondary" onClick={()=>setOneTimeKey(null)}>I saved it</Button></Card>:null}
 <Card><div className="flex items-center justify-between"><CardTitle>Status</CardTitle><Badge tone={status?.locked?'danger':'ok'}>{status?.locked?'Locked':'Available'}</Badge></div><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">User boxes</dt><dd>{status?.boxes??'—'}</dd></div><div><dt className="text-muted-foreground">Credentials</dt><dd>{status?.items??'—'}</dd></div><div><dt className="text-muted-foreground">Key version</dt><dd>{status?.keyVersion??'—'}</dd></div><div><dt className="text-muted-foreground">Recovery fingerprint</dt><dd>{status?.recoveryFingerprint??'Not initialized'}</dd></div><div><dt className="text-muted-foreground">Blocked jobs · 24h</dt><dd>{status?.recentFailures??'—'}{status?.lastFailureAt?` · last ${new Date(status.lastFailureAt).toLocaleString()}`:''}</dd></div></dl></Card>
 <Card><CardTitle>{status?.initialized?'Emergency lock':'Initialize Master Vault'}</CardTitle><p className="mb-3 text-sm text-muted-foreground">{status?.initialized?'Locking immediately stops Vault-backed credential jobs and clears every temporary UI unlock. Confirm with your password.':'Creates an independent random Master Vault key and one offline recovery key. Existing credentials are not imported automatically.'}</p><Input aria-label="Administrator password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/>{status?.initialized?<div className="mt-3 flex gap-2"><Button variant="danger" disabled={busy||!password||status?.locked} onClick={()=>void lock(true)}>Lock Master Vault</Button><Button disabled={busy||!password||!status?.locked} onClick={()=>void lock(false)}>Unlock</Button></div>:<Button className="mt-3" disabled={busy||!password} onClick={()=>void initialize()}>Initialize and show recovery key</Button>}</Card>
 {status?.initialized?<Card><CardTitle>Offline recovery</CardTitle><p className="mb-3 text-sm text-muted-foreground">Use only after restoring or replacing the installation key. Recovery re-wraps the same Vault key; it never reveals user secrets.</p><Input aria-label="Recovery key" type="password" value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value)}/><Button className="mt-3" disabled={busy||!password||!recoveryInput} onClick={()=>void recover()}>Recover Master Vault</Button></Card>:null}</div>;
}
