import { beforeEach, describe, expect, it } from 'vitest';
import { createUser } from '../../auth/src/users.js';
import { testDb, type TestDb } from './helpers.js';
import { MasterKey } from '../src/masterKey.js';
import { asSecret } from '../src/sealing.js';
import { checkVaultItem, getVaultSecret, initializeVault, listVaultItems, putVaultItem, rotateVaultBox, setVaultLock, VaultLockedError, vaultSecretSuffix, vaultStatus, verifyRecoveryKey } from '../src/vault.js';

let db:TestDb;let owner:string;const key=new MasterKey(Buffer.alloc(32,14));
beforeEach(async()=>{db=await testDb();owner=(await createUser(db,{email:'vault@example.test',username:'vault-owner',role:'super_admin'})).id;});

describe('Master Vault',()=>{
  it('previews the sensitive field rather than JSON wrapper punctuation',()=>{expect(vaultSecretSuffix(JSON.stringify({username:'roman',password:'correct-horse-9876'}))).toBe('9876');expect(vaultSecretSuffix(JSON.stringify({accessKeyId:'abc',secretAccessKey:'secret-4321'}))).toBe('4321');expect(vaultSecretSuffix('plain-secret-2468')).toBe('2468');});
  it('returns recovery material once, stores only its hash, and recovers the independent wrapping key',async()=>{const first=await initializeVault(db,key,owner);expect(first.recoveryKey.reveal()).not.toContain('[secret');await expect(initializeVault(db,key,owner)).rejects.toThrow(/already initialized/);const recovered=await verifyRecoveryKey(db,first.recoveryKey.reveal());expect(recovered.reveal()).not.toEqual(key.reveal());expect(recovered.reveal()).toHaveLength(32);const [row]=await db.query<{recovery_key_hash:string;recovery_master_enc:string}>(`select recovery_key_hash,recovery_master_enc from vault_state`);expect(JSON.stringify(row)).not.toContain(first.recoveryKey.reveal());});
  it('isolates boxes, masks listings, updates without corrupting context, and rotates',async()=>{await initializeVault(db,key,owner);const other=(await createUser(db,{email:'other@example.test',username:'other',role:'member'})).id;const item=await putVaultItem(db,key,{ownerUserId:owner,kind:'api_key',service:'example',slot:'main',label:'Example key',value:asSecret('credential-fixture-1234')});await putVaultItem(db,key,{ownerUserId:other,kind:'password',service:'example',slot:'main',label:'Other',value:asSecret('other-fixture-5678')});expect(await getVaultSecret(db,key,{ownerUserId:owner,service:'example',slot:'main'}).then(v=>v.reveal())).toBe('credential-fixture-1234');expect(JSON.stringify(await listVaultItems(db,owner))).not.toContain('credential-fixture');await putVaultItem(db,key,{ownerUserId:owner,kind:'api_key',service:'example',slot:'main',label:'Rotated',value:asSecret('replacement-fixture-9999')});expect((await listVaultItems(db,owner))[0].id).toBe(item.id);expect(await checkVaultItem(db,key,{ownerUserId:owner,itemId:item.id})).toBe(true);await rotateVaultBox(db,key,{ownerUserId:owner,actorUserId:owner});expect(await getVaultSecret(db,key,{ownerUserId:owner,service:'example',slot:'main'}).then(v=>v.reveal())).toBe('replacement-fixture-9999');expect((await listVaultItems(db,other))).toHaveLength(1);});
  it('fails closed while the master is locked',async()=>{await initializeVault(db,key,owner);await putVaultItem(db,key,{ownerUserId:owner,kind:'password',service:'site',slot:'login',label:'Site',value:asSecret('fixture-value')});await setVaultLock(db,{master:true,locked:true,actorUserId:owner});await expect(getVaultSecret(db,key,{ownerUserId:owner,service:'site',slot:'login'})).rejects.toBeInstanceOf(VaultLockedError);expect((await vaultStatus(db)).locked).toBe(true);});
});
