import { afterEach,beforeEach,describe,expect,it } from 'vitest';
import type {Server} from 'node:http';import type {AddressInfo} from 'node:net';import {mkdtempSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {testDb,type TestDb} from '../../../packages/core/test/helpers.js';import {createUser,ensureWorkspace} from './fixtures.js';import {createApp} from '../src/app.js';import {initializeVault,loadMasterKey} from '@josi-ce/core';
const dir=mkdtempSync(join(tmpdir(),'josi-vault-'));const keyPath=join(dir,'master.key');writeFileSync(keyPath,Buffer.alloc(32,19).toString('base64'));const PW='vault-password-long-enough';let db:TestDb,server:Server,base:string;const jars:Record<string,string>={};const ids:Record<string,string>={};
function merge(jar:string|undefined,cookies:string[]){const m=new Map<string,string>();for(const raw of [...(jar?[jar]:[]),...cookies])for(const part of raw.split(';')){const i=part.indexOf('=');if(i>0)m.set(part.slice(0,i).trim(),part.slice(i+1).trim());}return [...m].map(([k,v])=>`${k}=${v}`).join('; ');}
async function signIn(who:string){let r=await fetch(`${base}/api/auth/csrf`);let jar=merge(undefined,r.headers.getSetCookie());r=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json',cookie:jar,'x-josi-csrf':decodeURIComponent(/josi_csrf=([^;]+)/.exec(jar)?.[1]??'')},body:JSON.stringify({identifier:who,password:PW})});expect(r.status).toBe(200);return merge(jar,r.headers.getSetCookie());}
async function call(path:string,opts:{method?:string;body?:unknown;jar:string}){const method=opts.method??'GET';const headers:Record<string,string>={'content-type':'application/json',cookie:opts.jar};headers['x-josi-csrf']=decodeURIComponent(/josi_csrf=([^;]+)/.exec(opts.jar)?.[1]??'');const r=await fetch(`${base}${path}`,{method,headers,body:method==='GET'?undefined:JSON.stringify(opts.body??{})});return{status:r.status,body:await r.json().catch(()=>null)};}
beforeEach(async()=>{db=await testDb();await ensureWorkspace(db);ids.admin=(await createUser(db,{email:'admin@vault.test',username:'admin',role:'super_admin',password:PW})).id;ids.alice=(await createUser(db,{email:'alice@vault.test',username:'alice',role:'member',password:PW})).id;ids.bob=(await createUser(db,{email:'bob@vault.test',username:'bob',role:'member',password:PW})).id;await initializeVault(db,loadMasterKey({path:keyPath}),ids.admin);const app=createApp(db,{cookieSecure:false,appUrl:'http://localhost',masterKeyCheck:{path:keyPath}});await new Promise<void>(ok=>{server=app.listen(0,'127.0.0.1',ok);});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;jars.admin=await signIn('admin');jars.alice=await signIn('alice');jars.bob=await signIn('bob');});afterEach(()=>new Promise<void>(ok=>server.close(()=>ok())));
describe('Vault HTTP boundary',()=>{it('requires fresh password, never reveals a stored value, and isolates users',async()=>{expect((await call('/api/vault/unlock',{method:'POST',body:{password:'wrong'},jar:jars.alice})).status).toBe(401);expect((await call('/api/vault/unlock',{method:'POST',body:{password:PW},jar:jars.alice})).status).toBe(200);const saved=await call('/api/vault/items',{method:'POST',body:{kind:'password',service:'example',slot:'login',label:'Example login',value:'private-fixture-7788'},jar:jars.alice});expect(saved.status).toBe(201);const mine=await call('/api/vault',{jar:jars.alice});expect(JSON.stringify(mine.body)).not.toContain('private-fixture');expect(JSON.stringify(mine.body)).toContain('7788');const bob=await call('/api/vault',{jar:jars.bob});expect(JSON.stringify(bob.body)).not.toContain('Example login');});it('lets an admin control health but not enumerate user items',async()=>{const admin=await call('/api/admin/vault',{jar:jars.admin});expect(admin.status).toBe(200);expect(admin.body.status).not.toHaveProperty('itemsList');expect(JSON.stringify(admin.body)).not.toContain('value_enc');expect((await call('/api/admin/vault/lock',{method:'PUT',body:{password:PW,locked:true},jar:jars.admin})).status).toBe(200);expect((await call('/api/vault/unlock',{method:'POST',body:{password:PW},jar:jars.alice})).status).toBe(200);expect((await call('/api/vault/items',{method:'POST',body:{kind:'password',service:'x',slot:'x',label:'x',value:'xxxx'},jar:jars.alice})).status).toBe(423);});});
