import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { WorkspaceCode } from '@/components/WorkspaceCode';
import { api } from '@/lib/api';
interface Mapping {id:string;provider:string;display_path:string}
interface Entry {name:string;kind:string;size?:number;modified?:string}
interface Change {operation:string;path:string;destination?:string;content?:string}
export function LocalWorkspace() {
 const [mappings,setMappings]=useState<Mapping[]>([]),[id,setId]=useState(''),[path,setPath]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[filter,setFilter]=useState(''),[sort,setSort]=useState('asc');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[permissions,setPermissions]=useState<Record<string,boolean>>({});
 const [name,setName]=useState(''),[content,setContent]=useState(''),[destination,setDestination]=useState(''),[editing,setEditing]=useState(false),[pending,setPending]=useState<{id:string;change:Change}|null>(null),[receipt,setReceipt]=useState('');
 async function refresh(){if(!id)return;setBusy(true);setError('');try{const data=await api.get<{entries:Entry[];permissions:Record<string,boolean>}>(`/workspace/${id}/list?path=${encodeURIComponent(path)}`);setEntries(data.entries);setPermissions(data.permissions);}catch(e){setEntries([]);setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void api.get<{mappings:Mapping[]}>('/storage/mappings').then(x=>setMappings(x.mappings.filter(m=>m.provider==='local'))).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setPreview('');setPending(null);void refresh();},[id,path]);
 const full=(n:string)=>[path,n].filter(Boolean).join('/');
 async function propose(change:Change){setError('');try{const x=await api.post<{approval:{id:string}}>(`/workspace/${id}/change`,change);setPending({id:x.approval.id,change});}catch(e){setError((e as Error).message);}}
 return <main className="mx-auto w-full max-w-5xl space-y-4 p-4 sm:p-6"><h1 className="text-2xl font-semibold">Local Workspace</h1>
 <p>Browse folders you explicitly connected. Files are never instructions to grant access. <Link className="underline" to="/app/connections">Manage folder access</Link>.</p>
 {error&&<p role="alert" className="text-destructive">{error}</p>}{receipt&&<p role="status">Completed. Receipt: {receipt}</p>}
 <label className="block">Connected folder<select className="ml-2 rounded border bg-background p-2" value={id} onChange={e=>{setId(e.target.value);setPath('');setEntries([]);}}><option value="">Choose a folder</option>{mappings.map(m=><option key={m.id} value={m.id}>{m.display_path}</option>)}</select></label>
 {!mappings.length&&<p>No local folders connected. Ask your administrator to enable local mapping, then connect a configured root in Connections.</p>}
 {id&&<><nav aria-label="Workspace breadcrumbs" className="flex flex-wrap gap-2"><button className="underline" onClick={()=>setPath('')}>Folder root</button>{path.split('/').filter(Boolean).map((p,i,a)=><button className="underline" key={i} onClick={()=>setPath(a.slice(0,i+1).join('/'))}>/ {p}</button>)}</nav>
 <div className="flex flex-wrap gap-3"><label>Search this folder <input className="rounded border bg-background p-2" value={filter} onChange={e=>setFilter(e.target.value)}/></label><label>Sort <select className="rounded border bg-background p-2" value={sort} onChange={e=>setSort(e.target.value)}><option value="asc">Name A–Z</option><option value="desc">Name Z–A</option></select></label><button onClick={()=>void refresh()}>Refresh</button></div>
 {busy?<p role="status">Loading folder…</p>:<ul aria-label="Workspace files" className="divide-y">{entries.filter(e=>e.name.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>(sort==='asc'?1:-1)*a.name.localeCompare(b.name)).map(e=><li className="flex flex-wrap items-center gap-3 py-3" key={e.name}><span className="min-w-0 flex-1 break-all">{e.kind==='folder'?<button className="underline" onClick={()=>setPath(full(e.name))}>{e.name}/</button>:e.name}{e.size!==undefined&&<small className="block text-muted-foreground">{e.size} bytes{e.modified&&` · ${new Date(e.modified).toLocaleString()}`}</small>}</span>{e.kind==='file'&&<><a className="underline" href={`/api/workspace/${id}/file?path=${encodeURIComponent(full(e.name))}`}>Download</a><button onClick={()=>{void api.get<{text:string;size:number;modified:string}>(`/workspace/${id}/preview?path=${encodeURIComponent(full(e.name))}`).then(x=>setPreview(`${x.size} bytes · ${x.modified}\n\n${x.text}`)).catch(e=>setError(e.message));}}>Preview</button>{permissions.edit&&<button onClick={()=>{void api.get<{text:string}>(`/workspace/${id}/preview?path=${encodeURIComponent(full(e.name))}`).then(x=>{setName(e.name);setContent(x.text);setEditing(true);}).catch(e=>setError(e.message));}}>Edit text</button>}{permissions.move&&<button onClick={()=>{setName(e.name);setDestination(full(e.name));}}>Rename / move</button>}{permissions.delete&&<button onClick={()=>void propose({operation:'delete',path:full(e.name)})}>Delete…</button>}</>}</li>)}</ul>}
 {!busy&&!entries.length&&<p>This folder is empty.</p>}
 {preview&&<section aria-label="File preview"><button onClick={()=>setPreview('')}>Close preview</button><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words rounded border p-3">{preview}</pre></section>}
 {destination&&<form className="space-y-2 rounded border p-3" onSubmit={e=>{e.preventDefault();void propose({operation:'move',path:full(name),destination});}}><label>Destination relative to mapped root<input className="block w-full rounded border bg-background p-2" value={destination} onChange={e=>setDestination(e.target.value)}/></label><button type="submit">Review move</button><button type="button" onClick={()=>setDestination('')}>Cancel</button></form>}
 {(permissions.create||permissions.edit)&&<section className="space-y-3 rounded border p-3"><h2 className="font-semibold">Create or upload text</h2><label className="block">Filename<input className="ml-2 rounded border bg-background p-2" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">Contents<textarea className="block w-full rounded border bg-background p-2" value={content} onChange={e=>setContent(e.target.value)}/></label><label className="block">Upload text (256 KiB maximum)<input type="file" accept=".txt,.md,.csv,.json,.log" onChange={e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>262144){setError('File exceeds 256 KiB');return;}setName(f.name);void f.text().then(setContent);}}/></label><div className="flex gap-4"><button onClick={()=>void propose({operation:editing?'edit':'create',path:full(name),content})}>{editing?'Review text edit':'Review file creation'}</button>{permissions.create&&<button onClick={()=>void propose({operation:'mkdir',path:full(name)})}>Review folder creation</button>}{editing&&<button onClick={()=>setEditing(false)}>Create a new file instead</button>}</div></section>}
 <WorkspaceCode mappingId={id}/>
 {pending&&<section role="region" aria-label="Confirm workspace change" className="space-y-3 rounded border p-4"><h2 className="font-semibold">Confirm {pending.change.operation}</h2><p className="break-all">{pending.change.path}{pending.change.destination&&` → ${pending.change.destination}`}</p>{pending.change.operation==='delete'&&<p>This removes the file from this folder. A recovery copy is retained for the operator.</p>}{pending.change.content!==undefined&&<pre className="max-h-40 overflow-auto whitespace-pre-wrap">{pending.change.content}</pre>}<div className="flex gap-4"><button disabled={busy} onClick={()=>{setBusy(true);void api.post<{receipt:string}>(`/workspace/${id}/change/${pending.id}`,{...pending.change,confirm:true}).then(x=>{setReceipt(x.receipt);setPending(null);setDestination('');return refresh();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Approve exact change</button><button onClick={()=>setPending(null)}>Cancel</button></div></section>}
 </>}
 </main>;
}
